//! ISO 4217 currency codes
//! 
//! This crate provides an enum that represents all ISO 4217 currencies and 
//! has simple methods to convert between numeric and character code, list of 
//! territories where each currency is used, the symbol,
//! and the English name of the currency.
//! 
//! The data for this is taken from 
//! [https://en.wikipedia.org/wiki/ISO_4217](https://en.wikipedia.org/wiki/ISO_4217)
//! 
//! # Examples
//! 
//! ```
//! use iso_currency::Currency;
//! 
//! assert_eq!(Currency::EUR.name(), "Euro");
//! assert_eq!(Currency::EUR.numeric(), 978);
//! assert_eq!(Currency::from_numeric(978), Some(Currency::EUR));
//! assert_eq!(Currency::from_code("EUR"), Some(Currency::EUR));
//! assert_eq!(Currency::CHF.used_by(), vec!["Liechtenstein", "Switzerland"]);
//! assert_eq!(format!("{}", Currency::EUR.symbol()), "€");
//! ```

#[cfg(feature="serde")]
use serde::{Serialize, Deserialize};

#[cfg_attr(feature="serde", derive(Serialize, Deserialize))]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum Currency {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOV,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHE,
    CHF,
    CHW,
    CLF,
    CLP,
    CNY,
    COP,
    COU,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MXV,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    SSP,
    STN,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    USN,
    UYI,
    UYU,
    UYW,
    UZS,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XSU,
    XTS,
    XUA,
    XXX,
    YER,
    ZAR,
    ZMW,
    ZWL,
}

#[derive(PartialEq)]
pub struct CurrencySymbol {
    pub symbol: String,
    pub centesimal: Option<String>,
}

impl std::fmt::Debug for CurrencySymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.symbol)
    }
}

impl std::fmt::Display for CurrencySymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.symbol)
    }
}

impl CurrencySymbol {
    /// Represents the commonly used symbol for a currency
    /// 
    /// Data for the symbols was collected from
    /// [https://en.wikipedia.org/wiki/Currency_symbol#List_of_presently-circulating_currency_symbols]()
    /// 
    /// TODO: Add data about centesimal symbols for every currency
    /// TODO: Add data about English representations of some currency symbols
    /// TODO: Maybe add data about alternative variants of the symbols
    /// TODO: Add data about position of symbol (according to locale) when formatting a sum of money
    /// 
    pub fn new(symbol: &str, centesimal: Option<&str>) -> CurrencySymbol {
        CurrencySymbol {
            symbol: symbol.to_owned(),
            centesimal: match centesimal {
                Some(v) => Some(v.to_owned()),
                None => None,
            }
        }
    }
}

impl Currency {
    /// Returns the numeric code of the currency
    /// 
    /// This method will return the ISO 4217 numeric code of the currency
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(Currency::EUR.numeric(), 978);
    /// ```
    pub fn numeric(&self) -> u16 {
        match self {
            Currency::AED => 784,
            Currency::AFN => 971,
            Currency::ALL => 008,
            Currency::AMD => 051,
            Currency::ANG => 532,
            Currency::AOA => 973,
            Currency::ARS => 032,
            Currency::AUD => 036,
            Currency::AWG => 533,
            Currency::AZN => 944,
            Currency::BAM => 977,
            Currency::BBD => 052,
            Currency::BDT => 050,
            Currency::BGN => 975,
            Currency::BHD => 048,
            Currency::BIF => 108,
            Currency::BMD => 060,
            Currency::BND => 096,
            Currency::BOB => 068,
            Currency::BOV => 984,
            Currency::BRL => 986,
            Currency::BSD => 044,
            Currency::BTN => 064,
            Currency::BWP => 072,
            Currency::BYN => 933,
            Currency::BZD => 084,
            Currency::CAD => 124,
            Currency::CDF => 976,
            Currency::CHE => 947,
            Currency::CHF => 756,
            Currency::CHW => 948,
            Currency::CLF => 990,
            Currency::CLP => 152,
            Currency::CNY => 156,
            Currency::COP => 170,
            Currency::COU => 970,
            Currency::CRC => 188,
            Currency::CUC => 931,
            Currency::CUP => 192,
            Currency::CVE => 132,
            Currency::CZK => 203,
            Currency::DJF => 262,
            Currency::DKK => 208,
            Currency::DOP => 214,
            Currency::DZD => 012,
            Currency::EGP => 818,
            Currency::ERN => 232,
            Currency::ETB => 230,
            Currency::EUR => 978,
            Currency::FJD => 242,
            Currency::FKP => 238,
            Currency::GBP => 826,
            Currency::GEL => 981,
            Currency::GHS => 936,
            Currency::GIP => 292,
            Currency::GMD => 270,
            Currency::GNF => 324,
            Currency::GTQ => 320,
            Currency::GYD => 328,
            Currency::HKD => 344,
            Currency::HNL => 340,
            Currency::HRK => 191,
            Currency::HTG => 332,
            Currency::HUF => 348,
            Currency::IDR => 360,
            Currency::ILS => 376,
            Currency::INR => 356,
            Currency::IQD => 368,
            Currency::IRR => 364,
            Currency::ISK => 352,
            Currency::JMD => 388,
            Currency::JOD => 400,
            Currency::JPY => 392,
            Currency::KES => 404,
            Currency::KGS => 417,
            Currency::KHR => 116,
            Currency::KMF => 174,
            Currency::KPW => 408,
            Currency::KRW => 410,
            Currency::KWD => 414,
            Currency::KYD => 136,
            Currency::KZT => 398,
            Currency::LAK => 418,
            Currency::LBP => 422,
            Currency::LKR => 144,
            Currency::LRD => 430,
            Currency::LSL => 426,
            Currency::LYD => 434,
            Currency::MAD => 504,
            Currency::MDL => 498,
            Currency::MGA => 969,
            Currency::MKD => 807,
            Currency::MMK => 104,
            Currency::MNT => 496,
            Currency::MOP => 446,
            Currency::MRU => 929,
            Currency::MUR => 480,
            Currency::MVR => 462,
            Currency::MWK => 454,
            Currency::MXN => 484,
            Currency::MXV => 979,
            Currency::MYR => 458,
            Currency::MZN => 943,
            Currency::NAD => 516,
            Currency::NGN => 566,
            Currency::NIO => 558,
            Currency::NOK => 578,
            Currency::NPR => 524,
            Currency::NZD => 554,
            Currency::OMR => 512,
            Currency::PAB => 590,
            Currency::PEN => 604,
            Currency::PGK => 598,
            Currency::PHP => 608,
            Currency::PKR => 586,
            Currency::PLN => 985,
            Currency::PYG => 600,
            Currency::QAR => 634,
            Currency::RON => 946,
            Currency::RSD => 941,
            Currency::RUB => 643,
            Currency::RWF => 646,
            Currency::SAR => 682,
            Currency::SBD => 090,
            Currency::SCR => 690,
            Currency::SDG => 938,
            Currency::SEK => 752,
            Currency::SGD => 702,
            Currency::SHP => 654,
            Currency::SLL => 694,
            Currency::SOS => 706,
            Currency::SRD => 968,
            Currency::SSP => 728,
            Currency::STN => 930,
            Currency::SVC => 222,
            Currency::SYP => 760,
            Currency::SZL => 748,
            Currency::THB => 764,
            Currency::TJS => 972,
            Currency::TMT => 934,
            Currency::TND => 788,
            Currency::TOP => 776,
            Currency::TRY => 949,
            Currency::TTD => 780,
            Currency::TWD => 901,
            Currency::TZS => 834,
            Currency::UAH => 980,
            Currency::UGX => 800,
            Currency::USD => 840,
            Currency::USN => 997,
            Currency::UYI => 940,
            Currency::UYU => 858,
            Currency::UYW => 927,
            Currency::UZS => 860,
            Currency::VES => 928,
            Currency::VND => 704,
            Currency::VUV => 548,
            Currency::WST => 882,
            Currency::XAF => 950,
            Currency::XAG => 961,
            Currency::XAU => 959,
            Currency::XBA => 955,
            Currency::XBB => 956,
            Currency::XBC => 957,
            Currency::XBD => 958,
            Currency::XCD => 951,
            Currency::XDR => 960,
            Currency::XOF => 952,
            Currency::XPD => 964,
            Currency::XPF => 953,
            Currency::XPT => 962,
            Currency::XSU => 994,
            Currency::XTS => 963,
            Currency::XUA => 965,
            Currency::XXX => 999,
            Currency::YER => 886,
            Currency::ZAR => 710,
            Currency::ZMW => 967,
            Currency::ZWL => 932,
        }
    }

    /// Returns the name of the currency in English
    /// 
    /// This method will return the English name of the currency
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(Currency::EUR.name(), "Euro");
    /// ```
    pub fn name(&self) -> &str {
        match self {
            Currency::AED => "United Arab Emirates dirham",
            Currency::AFN => "Afghan afghani",
            Currency::ALL => "Albanian lek",
            Currency::AMD => "Armenian dram",
            Currency::ANG => "Netherlands Antillean guilder",
            Currency::AOA => "Angolan kwanza",
            Currency::ARS => "Argentine peso",
            Currency::AUD => "Australian dollar",
            Currency::AWG => "Aruban florin",
            Currency::AZN => "Azerbaijani manat",
            Currency::BAM => "Bosnia and Herzegovina convertible mark",
            Currency::BBD => "Barbados dollar",
            Currency::BDT => "Bangladeshi taka",
            Currency::BGN => "Bulgarian lev",
            Currency::BHD => "Bahraini dinar",
            Currency::BIF => "Burundian franc",
            Currency::BMD => "Bermudian dollar",
            Currency::BND => "Brunei dollar",
            Currency::BOB => "Boliviano",
            Currency::BOV => "Bolivian Mvdol",
            Currency::BRL => "Brazilian real",
            Currency::BSD => "Bahamian dollar",
            Currency::BTN => "Bhutanese ngultrum",
            Currency::BWP => "Botswana pula",
            Currency::BYN => "Belarusian ruble",
            Currency::BZD => "Belize dollar",
            Currency::CAD => "Canadian dollar",
            Currency::CDF => "Congolese franc",
            Currency::CHE => "WIR Euro",
            Currency::CHF => "Swiss franc",
            Currency::CHW => "WIR Franc",
            Currency::CLF => "Unidad de Fomento ",
            Currency::CLP => "Chilean peso",
            Currency::CNY => "Renminbi (Chinese) yuan",
            Currency::COP => "Colombian peso",
            Currency::COU => "Unidad de Valor Real (UVR)",
            Currency::CRC => "Costa Rican colon",
            Currency::CUC => "Cuban convertible peso",
            Currency::CUP => "Cuban peso",
            Currency::CVE => "Cape Verdean escudo",
            Currency::CZK => "Czech koruna",
            Currency::DJF => "Djiboutian franc",
            Currency::DKK => "Danish krone",
            Currency::DOP => "Dominican peso",
            Currency::DZD => "Algerian dinar",
            Currency::EGP => "Egyptian pound",
            Currency::ERN => "Eritrean nakfa",
            Currency::ETB => "Ethiopian birr",
            Currency::EUR => "Euro",
            Currency::FJD => "Fiji dollar",
            Currency::FKP => "Falkland Islands pound",
            Currency::GBP => "Pound sterling",
            Currency::GEL => "Georgian lari",
            Currency::GHS => "Ghanaian cedi",
            Currency::GIP => "Gibraltar pound",
            Currency::GMD => "Gambian dalasi",
            Currency::GNF => "Guinean franc",
            Currency::GTQ => "Guatemalan quetzal",
            Currency::GYD => "Guyanese dollar",
            Currency::HKD => "Hong Kong dollar",
            Currency::HNL => "Honduran lempira",
            Currency::HRK => "Croatian kuna",
            Currency::HTG => "Haitian gourde",
            Currency::HUF => "Hungarian forint",
            Currency::IDR => "Indonesian rupiah",
            Currency::ILS => "Israeli new shekel",
            Currency::INR => "Indian rupee",
            Currency::IQD => "Iraqi dinar",
            Currency::IRR => "Iranian rial",
            Currency::ISK => "Icelandic króna",
            Currency::JMD => "Jamaican dollar",
            Currency::JOD => "Jordanian dinar",
            Currency::JPY => "Japanese yen",
            Currency::KES => "Kenyan shilling",
            Currency::KGS => "Kyrgyzstani som",
            Currency::KHR => "Cambodian riel",
            Currency::KMF => "Comoro franc",
            Currency::KPW => "North Korean won",
            Currency::KRW => "South Korean won",
            Currency::KWD => "Kuwaiti dinar",
            Currency::KYD => "Cayman Islands dollar",
            Currency::KZT => "Kazakhstani tenge",
            Currency::LAK => "Lao kip",
            Currency::LBP => "Lebanese pound",
            Currency::LKR => "Sri Lankan rupee",
            Currency::LRD => "Liberian dollar",
            Currency::LSL => "Lesotho loti",
            Currency::LYD => "Libyan dinar",
            Currency::MAD => "Moroccan dirham",
            Currency::MDL => "Moldovan leu",
            Currency::MGA => "Malagasy ariary",
            Currency::MKD => "Macedonian denar",
            Currency::MMK => "Myanmar kyat",
            Currency::MNT => "Mongolian tögrög",
            Currency::MOP => "Macanese pataca",
            Currency::MRU => "Mauritanian ouguiya",
            Currency::MUR => "Mauritian rupee",
            Currency::MVR => "Maldivian rufiyaa",
            Currency::MWK => "Malawian kwacha",
            Currency::MXN => "Mexican peso",
            Currency::MXV => "Mexican Unidad de Inversion (UDI)",
            Currency::MYR => "Malaysian ringgit",
            Currency::MZN => "Mozambican metical",
            Currency::NAD => "Namibian dollar",
            Currency::NGN => "Nigerian naira",
            Currency::NIO => "Nicaraguan córdoba",
            Currency::NOK => "Norwegian krone",
            Currency::NPR => "Nepalese rupee",
            Currency::NZD => "New Zealand dollar",
            Currency::OMR => "Omani rial",
            Currency::PAB => "Panamanian balboa",
            Currency::PEN => "Peruvian sol",
            Currency::PGK => "Papua New Guinean kina",
            Currency::PHP => "Philippine peso",
            Currency::PKR => "Pakistani rupee",
            Currency::PLN => "Polish złoty",
            Currency::PYG => "Paraguayan guaraní",
            Currency::QAR => "Qatari riyal",
            Currency::RON => "Romanian leu",
            Currency::RSD => "Serbian dinar",
            Currency::RUB => "Russian ruble",
            Currency::RWF => "Rwandan franc",
            Currency::SAR => "Saudi riyal",
            Currency::SBD => "Solomon Islands dollar",
            Currency::SCR => "Seychelles rupee",
            Currency::SDG => "Sudanese pound",
            Currency::SEK => "Swedish krona/kronor",
            Currency::SGD => "Singapore dollar",
            Currency::SHP => "Saint Helena pound",
            Currency::SLL => "Sierra Leonean leone",
            Currency::SOS => "Somali shilling",
            Currency::SRD => "Surinamese dollar",
            Currency::SSP => "South Sudanese pound",
            Currency::STN => "São Tomé and Príncipe dobra",
            Currency::SVC => "Salvadoran colón",
            Currency::SYP => "Syrian pound",
            Currency::SZL => "Swazi lilangeni",
            Currency::THB => "Thai baht",
            Currency::TJS => "Tajikistani somoni",
            Currency::TMT => "Turkmenistan manat",
            Currency::TND => "Tunisian dinar",
            Currency::TOP => "Tongan paʻanga",
            Currency::TRY => "Turkish lira",
            Currency::TTD => "Trinidad and Tobago dollar",
            Currency::TWD => "New Taiwan dollar",
            Currency::TZS => "Tanzanian shilling",
            Currency::UAH => "Ukrainian hryvnia",
            Currency::UGX => "Ugandan shilling",
            Currency::USD => "United States dollar",
            Currency::USN => "United States dollar (next day)",
            Currency::UYI => "Uruguay Peso en Unidades Indexadas (URUIURUI)",
            Currency::UYU => "Uruguayan peso",
            Currency::UYW => "Unidad previsional[15]",
            Currency::UZS => "Uzbekistan som",
            Currency::VES => "Venezuelan bolívar soberano",
            Currency::VND => "Vietnamese đồng",
            Currency::VUV => "Vanuatu vatu",
            Currency::WST => "Samoan tala",
            Currency::XAF => "CFA franc BEAC",
            Currency::XAG => "Silver (one troy ounce)",
            Currency::XAU => "Gold (one troy ounce)",
            Currency::XBA => "European Composite Unit (EURCO)",
            Currency::XBB => "European Monetary Unit (E.M.U.-6)",
            Currency::XBC => "European Unit of Account 9 (E.U.A.-9)",
            Currency::XBD => "European Unit of Account 17 (E.U.A.-17)",
            Currency::XCD => "East Caribbean dollar",
            Currency::XDR => "Special drawing rights",
            Currency::XOF => "CFA franc BCEAO",
            Currency::XPD => "Palladium (one troy ounce)",
            Currency::XPF => "CFP franc (franc Pacifique)",
            Currency::XPT => "Platinum (one troy ounce)",
            Currency::XSU => "SUCRE",
            Currency::XTS => "Code reserved for testing",
            Currency::XUA => "ADB Unit of Account",
            Currency::XXX => "No currency",
            Currency::YER => "Yemeni rial",
            Currency::ZAR => "South African rand",
            Currency::ZMW => "Zambian kwacha",
            Currency::ZWL => "Zimbabwean dollar",
        }
    }

    /// Returns the ISO 4217 code
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(Currency::EUR.code(), "EUR");
    /// ```
    pub fn code(&self) -> &str {
        match self {
            Currency::AED => "AED",
            Currency::AFN => "AFN",
            Currency::ALL => "ALL",
            Currency::AMD => "AMD",
            Currency::ANG => "ANG",
            Currency::AOA => "AOA",
            Currency::ARS => "ARS",
            Currency::AUD => "AUD",
            Currency::AWG => "AWG",
            Currency::AZN => "AZN",
            Currency::BAM => "BAM",
            Currency::BBD => "BBD",
            Currency::BDT => "BDT",
            Currency::BGN => "BGN",
            Currency::BHD => "BHD",
            Currency::BIF => "BIF",
            Currency::BMD => "BMD",
            Currency::BND => "BND",
            Currency::BOB => "BOB",
            Currency::BOV => "BOV",
            Currency::BRL => "BRL",
            Currency::BSD => "BSD",
            Currency::BTN => "BTN",
            Currency::BWP => "BWP",
            Currency::BYN => "BYN",
            Currency::BZD => "BZD",
            Currency::CAD => "CAD",
            Currency::CDF => "CDF",
            Currency::CHE => "CHE",
            Currency::CHF => "CHF",
            Currency::CHW => "CHW",
            Currency::CLF => "CLF",
            Currency::CLP => "CLP",
            Currency::CNY => "CNY",
            Currency::COP => "COP",
            Currency::COU => "COU",
            Currency::CRC => "CRC",
            Currency::CUC => "CUC",
            Currency::CUP => "CUP",
            Currency::CVE => "CVE",
            Currency::CZK => "CZK",
            Currency::DJF => "DJF",
            Currency::DKK => "DKK",
            Currency::DOP => "DOP",
            Currency::DZD => "DZD",
            Currency::EGP => "EGP",
            Currency::ERN => "ERN",
            Currency::ETB => "ETB",
            Currency::EUR => "EUR",
            Currency::FJD => "FJD",
            Currency::FKP => "FKP",
            Currency::GBP => "GBP",
            Currency::GEL => "GEL",
            Currency::GHS => "GHS",
            Currency::GIP => "GIP",
            Currency::GMD => "GMD",
            Currency::GNF => "GNF",
            Currency::GTQ => "GTQ",
            Currency::GYD => "GYD",
            Currency::HKD => "HKD",
            Currency::HNL => "HNL",
            Currency::HRK => "HRK",
            Currency::HTG => "HTG",
            Currency::HUF => "HUF",
            Currency::IDR => "IDR",
            Currency::ILS => "ILS",
            Currency::INR => "INR",
            Currency::IQD => "IQD",
            Currency::IRR => "IRR",
            Currency::ISK => "ISK",
            Currency::JMD => "JMD",
            Currency::JOD => "JOD",
            Currency::JPY => "JPY",
            Currency::KES => "KES",
            Currency::KGS => "KGS",
            Currency::KHR => "KHR",
            Currency::KMF => "KMF",
            Currency::KPW => "KPW",
            Currency::KRW => "KRW",
            Currency::KWD => "KWD",
            Currency::KYD => "KYD",
            Currency::KZT => "KZT",
            Currency::LAK => "LAK",
            Currency::LBP => "LBP",
            Currency::LKR => "LKR",
            Currency::LRD => "LRD",
            Currency::LSL => "LSL",
            Currency::LYD => "LYD",
            Currency::MAD => "MAD",
            Currency::MDL => "MDL",
            Currency::MGA => "MGA",
            Currency::MKD => "MKD",
            Currency::MMK => "MMK",
            Currency::MNT => "MNT",
            Currency::MOP => "MOP",
            Currency::MRU => "MRU",
            Currency::MUR => "MUR",
            Currency::MVR => "MVR",
            Currency::MWK => "MWK",
            Currency::MXN => "MXN",
            Currency::MXV => "MXV",
            Currency::MYR => "MYR",
            Currency::MZN => "MZN",
            Currency::NAD => "NAD",
            Currency::NGN => "NGN",
            Currency::NIO => "NIO",
            Currency::NOK => "NOK",
            Currency::NPR => "NPR",
            Currency::NZD => "NZD",
            Currency::OMR => "OMR",
            Currency::PAB => "PAB",
            Currency::PEN => "PEN",
            Currency::PGK => "PGK",
            Currency::PHP => "PHP",
            Currency::PKR => "PKR",
            Currency::PLN => "PLN",
            Currency::PYG => "PYG",
            Currency::QAR => "QAR",
            Currency::RON => "RON",
            Currency::RSD => "RSD",
            Currency::RUB => "RUB",
            Currency::RWF => "RWF",
            Currency::SAR => "SAR",
            Currency::SBD => "SBD",
            Currency::SCR => "SCR",
            Currency::SDG => "SDG",
            Currency::SEK => "SEK",
            Currency::SGD => "SGD",
            Currency::SHP => "SHP",
            Currency::SLL => "SLL",
            Currency::SOS => "SOS",
            Currency::SRD => "SRD",
            Currency::SSP => "SSP",
            Currency::STN => "STN",
            Currency::SVC => "SVC",
            Currency::SYP => "SYP",
            Currency::SZL => "SZL",
            Currency::THB => "THB",
            Currency::TJS => "TJS",
            Currency::TMT => "TMT",
            Currency::TND => "TND",
            Currency::TOP => "TOP",
            Currency::TRY => "TRY",
            Currency::TTD => "TTD",
            Currency::TWD => "TWD",
            Currency::TZS => "TZS",
            Currency::UAH => "UAH",
            Currency::UGX => "UGX",
            Currency::USD => "USD",
            Currency::USN => "USN",
            Currency::UYI => "UYI",
            Currency::UYU => "UYU",
            Currency::UYW => "UYW",
            Currency::UZS => "UZS",
            Currency::VES => "VES",
            Currency::VND => "VND",
            Currency::VUV => "VUV",
            Currency::WST => "WST",
            Currency::XAF => "XAF",
            Currency::XAG => "XAG",
            Currency::XAU => "XAU",
            Currency::XBA => "XBA",
            Currency::XBB => "XBB",
            Currency::XBC => "XBC",
            Currency::XBD => "XBD",
            Currency::XCD => "XCD",
            Currency::XDR => "XDR",
            Currency::XOF => "XOF",
            Currency::XPD => "XPD",
            Currency::XPF => "XPF",
            Currency::XPT => "XPT",
            Currency::XSU => "XSU",
            Currency::XTS => "XTS",
            Currency::XUA => "XUA",
            Currency::XXX => "XXX",
            Currency::YER => "YER",
            Currency::ZAR => "ZAR",
            Currency::ZMW => "ZMW",
            Currency::ZWL => "ZWL",
        }
    }

    /// Returns a list of locations which use the currency
    /// 
    /// This method will return a list of locations which use the currency.
    /// The use is non-exclusive, so it might mean that the location is using
    /// other currencies as well. The list of locations is sorted.
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(
    ///     Currency::CHF.used_by(),
    ///     vec!["Liechtenstein", "Switzerland"]
    /// );
    /// ```
    pub fn used_by(&self) -> Vec<&str> {
        let mut territories = match self {
            Currency::AED => vec!["United Arab Emirates"],
            Currency::AFN => vec!["Afghanistan"],
            Currency::ALL => vec!["Albania"],
            Currency::AMD => vec!["Armenia"],
            Currency::ANG => vec!["Curaçao", "Sint Maarten"],
            Currency::AOA => vec!["Angola"],
            Currency::ARS => vec!["Argentina"],
            Currency::AUD => vec![
                "Australia",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Heard Island and McDonald Islands",
                "Kiribati",
                "Nauru",
                "Norfolk Island",
                "Tuvalu",
            ],
            Currency::AWG => vec!["Aruba"],
            Currency::AZN => vec!["Azerbaijan"],
            Currency::BAM => vec!["Bosnia and Herzegovina"],
            Currency::BBD => vec!["Barbados"],
            Currency::BDT => vec!["Bangladesh"],
            Currency::BGN => vec!["Bulgaria"],
            Currency::BHD => vec!["Bahrain"],
            Currency::BIF => vec!["Burundi"],
            Currency::BMD => vec!["Bermuda"],
            Currency::BND => vec!["Brunei"],
            Currency::BOB => vec!["Bolivia"],
            Currency::BOV => vec!["Bolivia"],
            Currency::BRL => vec!["Brazil"],
            Currency::BSD => vec!["Bahamas"],
            Currency::BTN => vec!["Bhutan"],
            Currency::BWP => vec!["Botswana"],
            Currency::BYN => vec!["Belarus"],
            Currency::BZD => vec!["Belize"],
            Currency::CAD => vec!["Canada"],
            Currency::CDF => vec!["Democratic Republic of the Congo"],
            Currency::CHE => vec!["Switzerland"],
            Currency::CHF => vec!["Switzerland", "Liechtenstein"],
            Currency::CHW => vec!["Switzerland"],
            Currency::CLF => vec!["Chile"],
            Currency::CLP => vec!["Chile"],
            Currency::CNY => vec!["China"],
            Currency::COP => vec!["Colombia"],
            Currency::COU => vec!["Colombia"],
            Currency::CRC => vec!["Costa Rica"],
            Currency::CUC => vec!["Cuba"],
            Currency::CUP => vec!["Cuba"],
            Currency::CVE => vec!["Cabo Verde"],
            Currency::CZK => vec!["Czechia [9]"],
            Currency::DJF => vec!["Djibouti"],
            Currency::DKK => vec!["Denmark", "Faroe Islands", "Greenland"],
            Currency::DOP => vec!["Dominican Republic"],
            Currency::DZD => vec!["Algeria"],
            Currency::EGP => vec!["Egypt"],
            Currency::ERN => vec!["Eritrea"],
            Currency::ETB => vec!["Ethiopia"],
            Currency::EUR => vec![
                "Åland Islands",
                "Andorra",
                "Austria",
                "Belgium",
                "Cyprus",
                "Estonia",
                "Finland",
                "France",
                "French Southern and Antarctic Lands",
                "Germany",
                "Greece",
                "Guadeloupe",
                "Ireland",
                "Italy",
                "Latvia",
                "Lithuania",
                "Luxembourg",
                "Malta",
                "French Guiana",
                "Martinique",
                "Mayotte",
                "Monaco",
                "Montenegro",
                "Netherlands",
                "Portugal",
                "Réunion",
                "Saint Barthélemy",
                "Saint Martin",
                "Saint Pierre and Miquelon",
                "San Marino",
                "Slovakia",
                "Slovenia",
                "Spain",
                "Holy See",
            ],
            Currency::FJD => vec!["Fiji"],
            Currency::FKP => vec!["Falkland Islands"],
            Currency::GBP => vec![
                "United Kingdom",
                "British Indian Ocean Territory",
                "Isle of Man",
                "Jersey",
                "Guernsey",
            ],
            Currency::GEL => vec!["Georgia"],
            Currency::GHS => vec!["Ghana"],
            Currency::GIP => vec!["Gibraltar"],
            Currency::GMD => vec!["Gambia"],
            Currency::GNF => vec!["Guinea"],
            Currency::GTQ => vec!["Guatemala"],
            Currency::GYD => vec!["Guyana"],
            Currency::HKD => vec!["Hong Kong"],
            Currency::HNL => vec!["Honduras"],
            Currency::HRK => vec!["Croatia"],
            Currency::HTG => vec!["Haiti"],
            Currency::HUF => vec!["Hungary"],
            Currency::IDR => vec!["Indonesia"],
            Currency::ILS => vec!["Israel", "Palestinian Authority"],
            Currency::INR => vec!["India", "Bhutan"],
            Currency::IQD => vec!["Iraq"],
            Currency::IRR => vec!["Iran"],
            Currency::ISK => vec!["Iceland"],
            Currency::JMD => vec!["Jamaica"],
            Currency::JOD => vec!["Jordan"],
            Currency::JPY => vec!["Japan"],
            Currency::KES => vec!["Kenya"],
            Currency::KGS => vec!["Kyrgyzstan"],
            Currency::KHR => vec!["Cambodia"],
            Currency::KMF => vec!["Comoros"],
            Currency::KPW => vec!["North Korea"],
            Currency::KRW => vec!["South Korea"],
            Currency::KWD => vec!["Kuwait"],
            Currency::KYD => vec!["Cayman Islands"],
            Currency::KZT => vec!["Kazakhstan"],
            Currency::LAK => vec!["Laos"],
            Currency::LBP => vec!["Lebanon"],
            Currency::LKR => vec!["Sri Lanka"],
            Currency::LRD => vec!["Liberia"],
            Currency::LSL => vec!["Lesotho"],
            Currency::LYD => vec!["Libya"],
            Currency::MAD => vec!["Morocco", "Western Sahara"],
            Currency::MDL => vec!["Moldova"],
            Currency::MGA => vec!["Madagascar"],
            Currency::MKD => vec!["North Macedonia"],
            Currency::MMK => vec!["Myanmar"],
            Currency::MNT => vec!["Mongolia"],
            Currency::MOP => vec!["Macau"],
            Currency::MRU => vec!["Mauritania"],
            Currency::MUR => vec!["Mauritius"],
            Currency::MVR => vec!["Maldives"],
            Currency::MWK => vec!["Malawi"],
            Currency::MXN => vec!["Mexico"],
            Currency::MXV => vec!["Mexico"],
            Currency::MYR => vec!["Malaysia"],
            Currency::MZN => vec!["Mozambique"],
            Currency::NAD => vec!["Namibia"],
            Currency::NGN => vec!["Nigeria"],
            Currency::NIO => vec!["Nicaragua"],
            Currency::NOK => vec!["Norway", "Svalbard", "Jan Mayen", "Bouvet Island"],
            Currency::NPR => vec!["Nepal"],
            Currency::NZD => vec![
                "New Zealand",
                "Cook Islands",
                "Niue",
                "Pitcairn Islands",
                "Tokelau",
            ],
            Currency::OMR => vec!["Oman"],
            Currency::PAB => vec!["Panama"],
            Currency::PEN => vec!["Peru"],
            Currency::PGK => vec!["Papua New Guinea"],
            Currency::PHP => vec!["Philippines"],
            Currency::PKR => vec!["Pakistan"],
            Currency::PLN => vec!["Poland"],
            Currency::PYG => vec!["Paraguay"],
            Currency::QAR => vec!["Qatar"],
            Currency::RON => vec!["Romania"],
            Currency::RSD => vec!["Serbia"],
            Currency::RUB => vec!["Russia"],
            Currency::RWF => vec!["Rwanda"],
            Currency::SAR => vec!["Saudi Arabia"],
            Currency::SBD => vec!["Solomon Islands"],
            Currency::SCR => vec!["Seychelles"],
            Currency::SDG => vec!["Sudan"],
            Currency::SEK => vec!["Sweden"],
            Currency::SGD => vec!["Singapore"],
            Currency::SHP => vec!["Saint Helena", "Ascension Island", "Tristan da Cunha"],
            Currency::SLL => vec!["Sierra Leone"],
            Currency::SOS => vec!["Somalia"],
            Currency::SRD => vec!["Suriname"],
            Currency::SSP => vec!["South Sudan"],
            Currency::STN => vec!["São Tomé and Príncipe"],
            Currency::SVC => vec!["El Salvador"],
            Currency::SYP => vec!["Syria"],
            Currency::SZL => vec!["Eswatini[13]"],
            Currency::THB => vec!["Thailand"],
            Currency::TJS => vec!["Tajikistan"],
            Currency::TMT => vec!["Turkmenistan"],
            Currency::TND => vec!["Tunisia"],
            Currency::TOP => vec!["Tonga"],
            Currency::TRY => vec!["Turkey"],
            Currency::TTD => vec!["Trinidad and Tobago"],
            Currency::TWD => vec!["Taiwan"],
            Currency::TZS => vec!["Tanzania"],
            Currency::UAH => vec!["Ukraine"],
            Currency::UGX => vec!["Uganda"],
            Currency::USD => vec![
                "United States",
                "American Samoa",
                "Barbados",
                "Bermuda",
                "British Indian Ocean Territory",
                "British Virgin Islands",
                "Caribbean Netherlands",
                "Ecuador",
                "El Salvador",
                "Guam",
                "Haiti",
                "Marshall Islands",
                "Federated States of Micronesia",
                "Northern Mariana Islands",
                "Palau",
                "Panama",
                "Puerto Rico",
                "Timor-Leste",
                "Turks and Caicos Islands",
                "U.S. Virgin Islands",
                "United States Minor Outlying Islands",
                "Cambodia",
            ],
            Currency::USN => vec!["United States"],
            Currency::UYI => vec!["Uruguay"],
            Currency::UYU => vec!["Uruguay"],
            Currency::UYW => vec!["Uruguay"],
            Currency::UZS => vec!["Uzbekistan"],
            Currency::VES => vec!["Venezuela"],
            Currency::VND => vec!["Vietnam"],
            Currency::VUV => vec!["Vanuatu"],
            Currency::WST => vec!["Samoa"],
            Currency::XAF => vec![
                "Cameroon",
                "Central African Republic",
                "Republic of the Congo",
                "Chad",
                "Equatorial Guinea",
                "Gabon",
            ],
            Currency::XAG => vec![],
            Currency::XAU => vec![],
            Currency::XBA => vec![],
            Currency::XBB => vec![],
            Currency::XBC => vec![],
            Currency::XBD => vec![],
            Currency::XCD => vec![
                "Anguilla",
                "Antigua and Barbuda",
                "Dominica",
                "Grenada",
                "Montserrat",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Vincent and the Grenadines",
            ],
            Currency::XDR => vec!["International Monetary Fund"],
            Currency::XOF => vec![
                "Benin",
                "Burkina Faso",
                "Côte d'Ivoire",
                "Guinea-Bissau",
                "Mali",
                "Niger",
                "Senegal",
                "Togo",
            ],
            Currency::XPD => vec![],
            Currency::XPF => vec!["French Polynesia", "New Caledonia", "Wallis and Futuna"],
            Currency::XPT => vec![],
            Currency::XSU => vec!["Unified System for Regional Compensation (SUCRE)"],
            Currency::XTS => vec![],
            Currency::XUA => vec!["African Development Bank"],
            Currency::XXX => vec![],
            Currency::YER => vec!["Yemen"],
            Currency::ZAR => vec!["Lesotho", "Namibia", "South Africa"],
            Currency::ZMW => vec!["Zambia"],
            Currency::ZWL => vec!["Zimbabwe"],
        };

        territories.sort();
        territories
    }

    /// Returns the currency's symbol
    /// 
    /// This method will return the symbol commonly used to represent the 
    /// currency. In case there is no symbol associated the international
    /// currency symbol will be returned.
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(format!("{}", Currency::EUR.symbol()), "€");
    /// assert_eq!(format!("{}", Currency::XXX.symbol()), "¤");
    /// ```
    pub fn symbol(&self) -> CurrencySymbol {
        match self {
            Currency::AED => CurrencySymbol::new("د.إ", None),
            Currency::AFN => CurrencySymbol::new("؋", None),
            Currency::ALL => CurrencySymbol::new("L", Some("q")),
            Currency::AMD => CurrencySymbol::new("֏", None),
            Currency::ANG => CurrencySymbol::new("ƒ", None),
            Currency::AOA => CurrencySymbol::new("Kz", None),
            Currency::ARS => CurrencySymbol::new("$", None),
            Currency::AUD => CurrencySymbol::new("$", Some("c")),
            Currency::AWG => CurrencySymbol::new("ƒ", None),
            Currency::AZN => CurrencySymbol::new("₼", None),
            Currency::BAM => CurrencySymbol::new("KM", None),
            Currency::BBD => CurrencySymbol::new("Bds$", None),
            Currency::BDT => CurrencySymbol::new("৳", None),
            Currency::BGN => CurrencySymbol::new("лв.", None),
            Currency::BHD => CurrencySymbol::new(".د.ب", None),
            Currency::BIF => CurrencySymbol::new("FBu", None),
            Currency::BMD => CurrencySymbol::new("$", None),
            Currency::BND => CurrencySymbol::new("B$", None),
            Currency::BOB => CurrencySymbol::new("Bs.", None),
            Currency::BRL => CurrencySymbol::new("R$", None),
            Currency::BSD => CurrencySymbol::new("$", None),
            Currency::BTN => CurrencySymbol::new("Nu.", Some("Ch.")),
            Currency::BWP => CurrencySymbol::new("P", None),
            Currency::BYN => CurrencySymbol::new("Br", None),
            Currency::BZD => CurrencySymbol::new("$", None),
            Currency::CAD => CurrencySymbol::new("$", Some("¢")),
            Currency::CDF => CurrencySymbol::new("₣", None),
            Currency::CHF => CurrencySymbol::new("₣", None),
            Currency::CLP => CurrencySymbol::new("$", None),
            Currency::CNY => CurrencySymbol::new("¥", None),
            Currency::COP => CurrencySymbol::new("$", None),
            Currency::CRC => CurrencySymbol::new("₡", None),
            Currency::CUC => CurrencySymbol::new("$", None),
            Currency::CUP => CurrencySymbol::new("₱", None),
            Currency::CVE => CurrencySymbol::new("Esc", None),
            Currency::CZK => CurrencySymbol::new("Kč", Some("h")),
            Currency::DJF => CurrencySymbol::new("₣", None),
            Currency::DKK => CurrencySymbol::new("kr", None),
            Currency::DOP => CurrencySymbol::new("RD$", None),
            Currency::DZD => CurrencySymbol::new("دج", None),
            Currency::EGP => CurrencySymbol::new("£", Some("pt")),
            Currency::ERN => CurrencySymbol::new("Nfk", None),
            Currency::ETB => CurrencySymbol::new("Br", None),
            Currency::EUR => CurrencySymbol::new("€", None),
            Currency::FJD => CurrencySymbol::new("FJ$", None),
            Currency::FKP => CurrencySymbol::new("£", None),
            Currency::GBP => CurrencySymbol::new("£", Some("p")),
            Currency::GEL => CurrencySymbol::new("ლ", None),
            Currency::GHS => CurrencySymbol::new("GH₵", None),
            Currency::GIP => CurrencySymbol::new("£", None),
            Currency::GMD => CurrencySymbol::new("D", None),
            Currency::GNF => CurrencySymbol::new("₣", None),
            Currency::GTQ => CurrencySymbol::new("Q", None),
            Currency::GYD => CurrencySymbol::new("G$", None),
            Currency::HKD => CurrencySymbol::new("HK$", None),
            Currency::HNL => CurrencySymbol::new("L", None),
            Currency::HRK => CurrencySymbol::new("kn", Some("lp")),
            Currency::HTG => CurrencySymbol::new("G", None),
            Currency::HUF => CurrencySymbol::new("Ft", None),
            Currency::IDR => CurrencySymbol::new("Rp", None),
            Currency::ILS => CurrencySymbol::new("₪", None),
            Currency::INR => CurrencySymbol::new("₹", None),
            Currency::IQD => CurrencySymbol::new("د.ع", None),
            Currency::IRR => CurrencySymbol::new("﷼", None),
            Currency::ISK => CurrencySymbol::new("kr", None),
            Currency::JMD => CurrencySymbol::new("$", None),
            Currency::JOD => CurrencySymbol::new("JD", None),
            Currency::JPY => CurrencySymbol::new("¥", None),
            Currency::KES => CurrencySymbol::new("Ksh", None),
            Currency::KGS => CurrencySymbol::new("С̲", None),
            Currency::KHR => CurrencySymbol::new("៛", None),
            Currency::KMF => CurrencySymbol::new("₣", None),
            Currency::KPW => CurrencySymbol::new("₩", None),
            Currency::KRW => CurrencySymbol::new("₩", None),
            Currency::KWD => CurrencySymbol::new("د.ك", None),
            Currency::KYD => CurrencySymbol::new("$", None),
            Currency::KZT => CurrencySymbol::new("₸", None),
            Currency::LAK => CurrencySymbol::new("₭", None),
            Currency::LBP => CurrencySymbol::new("LL", None),
            Currency::LKR => CurrencySymbol::new("₨", None),
            Currency::LRD => CurrencySymbol::new("L$", None),
            Currency::LSL => CurrencySymbol::new("M", None),
            Currency::LYD => CurrencySymbol::new("ل.د", None),
            Currency::MAD => CurrencySymbol::new("د.م.", None),
            Currency::MGA => CurrencySymbol::new("Ar", None),
            Currency::MKD => CurrencySymbol::new("ден", None),
            Currency::MMK => CurrencySymbol::new("K", None),
            Currency::MNT => CurrencySymbol::new("₮", None),
            Currency::MOP => CurrencySymbol::new("MOP$", None),
            Currency::MRU => CurrencySymbol::new("UM", None),
            Currency::MUR => CurrencySymbol::new("₨", None),
            Currency::MVR => CurrencySymbol::new("Rf.", None),
            Currency::MWK => CurrencySymbol::new("K", None),
            Currency::MXN => CurrencySymbol::new("$", Some("¢")),
            Currency::MYR => CurrencySymbol::new("RM", None),
            Currency::MZN => CurrencySymbol::new("MT", None),
            Currency::NAD => CurrencySymbol::new("N$", None),
            Currency::NGN => CurrencySymbol::new("₦", None),
            Currency::NIO => CurrencySymbol::new("C$", None),
            Currency::NOK => CurrencySymbol::new("kr", None),
            Currency::NPR => CurrencySymbol::new("₨", None),
            Currency::NZD => CurrencySymbol::new("$", Some("c")),
            Currency::OMR => CurrencySymbol::new("ر.ع.", None),
            Currency::PAB => CurrencySymbol::new("B/.", None),
            Currency::PEN => CurrencySymbol::new("S/", None),
            Currency::PGK => CurrencySymbol::new("K", None),
            Currency::PHP => CurrencySymbol::new("₱", None),
            Currency::PKR => CurrencySymbol::new("₨", None),
            Currency::PLN => CurrencySymbol::new("zł", Some("gr")),
            Currency::PYG => CurrencySymbol::new("₲", None),
            Currency::QAR => CurrencySymbol::new("ر.ق", None),
            Currency::RSD => CurrencySymbol::new("дин", None),
            Currency::RUB => CurrencySymbol::new("₽", None),
            Currency::RWF => CurrencySymbol::new("FRw", None),
            Currency::SAR => CurrencySymbol::new("ر.س", None),
            Currency::SBD => CurrencySymbol::new("S$", None),
            Currency::SCR => CurrencySymbol::new("SRe", None),
            Currency::SEK => CurrencySymbol::new("kr", None),
            Currency::SHP => CurrencySymbol::new("£", None),
            Currency::SLL => CurrencySymbol::new("Le", None),
            Currency::SOS => CurrencySymbol::new("Sh.So.", None),
            Currency::SRD => CurrencySymbol::new("$", None),
            Currency::STN => CurrencySymbol::new("Db", None),
            Currency::SYP => CurrencySymbol::new("LS", None),
            Currency::SZL => CurrencySymbol::new("E", None),
            Currency::THB => CurrencySymbol::new("฿", None),
            Currency::TND => CurrencySymbol::new("د.ت", None),
            Currency::TOP => CurrencySymbol::new("T$", None),
            Currency::TRY => CurrencySymbol::new("₺", None),
            Currency::TTD => CurrencySymbol::new("$", None),
            Currency::TWD => CurrencySymbol::new("NT$", None),
            Currency::TZS => CurrencySymbol::new("Tsh", None),
            Currency::UAH => CurrencySymbol::new("₴", None),
            Currency::UGX => CurrencySymbol::new("USh", None),
            Currency::USD => CurrencySymbol::new("$", Some("¢")),
            Currency::UYU => CurrencySymbol::new("$U", None),
            Currency::VES => CurrencySymbol::new("Bs.", None),
            Currency::VND => CurrencySymbol::new("₫", None),
            Currency::VUV => CurrencySymbol::new("VT", None),
            Currency::WST => CurrencySymbol::new("WS$", None),
            Currency::XAF => CurrencySymbol::new("FCFA", None),
            Currency::XCD => CurrencySymbol::new("$", None),
            Currency::XDR => CurrencySymbol::new("SDR", None),
            Currency::XOF => CurrencySymbol::new("CFA", None),
            Currency::XPF => CurrencySymbol::new("₣", None),
            Currency::YER => CurrencySymbol::new("ر.ي", None),
            Currency::ZAR => CurrencySymbol::new("R", None),
            Currency::ZMW => CurrencySymbol::new("K", None),
            _ => CurrencySymbol::new("¤", None),
        }
    }

    /// Create a currency instance from a ISO 4217 character code
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(Currency::from_code("EUR"), Some(Currency::EUR));
    /// ```
    pub fn from_code(code: &str) -> Option<Currency> {
        if code.len() != 3 {
            return None;
        }

        match code {
            "AED" => Some(Currency::AED),
            "AFN" => Some(Currency::AFN),
            "ALL" => Some(Currency::ALL),
            "AMD" => Some(Currency::AMD),
            "ANG" => Some(Currency::ANG),
            "AOA" => Some(Currency::AOA),
            "ARS" => Some(Currency::ARS),
            "AUD" => Some(Currency::AUD),
            "AWG" => Some(Currency::AWG),
            "AZN" => Some(Currency::AZN),
            "BAM" => Some(Currency::BAM),
            "BBD" => Some(Currency::BBD),
            "BDT" => Some(Currency::BDT),
            "BGN" => Some(Currency::BGN),
            "BHD" => Some(Currency::BHD),
            "BIF" => Some(Currency::BIF),
            "BMD" => Some(Currency::BMD),
            "BND" => Some(Currency::BND),
            "BOB" => Some(Currency::BOB),
            "BOV" => Some(Currency::BOV),
            "BRL" => Some(Currency::BRL),
            "BSD" => Some(Currency::BSD),
            "BTN" => Some(Currency::BTN),
            "BWP" => Some(Currency::BWP),
            "BYN" => Some(Currency::BYN),
            "BZD" => Some(Currency::BZD),
            "CAD" => Some(Currency::CAD),
            "CDF" => Some(Currency::CDF),
            "CHE" => Some(Currency::CHE),
            "CHF" => Some(Currency::CHF),
            "CHW" => Some(Currency::CHW),
            "CLF" => Some(Currency::CLF),
            "CLP" => Some(Currency::CLP),
            "CNY" => Some(Currency::CNY),
            "COP" => Some(Currency::COP),
            "COU" => Some(Currency::COU),
            "CRC" => Some(Currency::CRC),
            "CUC" => Some(Currency::CUC),
            "CUP" => Some(Currency::CUP),
            "CVE" => Some(Currency::CVE),
            "CZK" => Some(Currency::CZK),
            "DJF" => Some(Currency::DJF),
            "DKK" => Some(Currency::DKK),
            "DOP" => Some(Currency::DOP),
            "DZD" => Some(Currency::DZD),
            "EGP" => Some(Currency::EGP),
            "ERN" => Some(Currency::ERN),
            "ETB" => Some(Currency::ETB),
            "EUR" => Some(Currency::EUR),
            "FJD" => Some(Currency::FJD),
            "FKP" => Some(Currency::FKP),
            "GBP" => Some(Currency::GBP),
            "GEL" => Some(Currency::GEL),
            "GHS" => Some(Currency::GHS),
            "GIP" => Some(Currency::GIP),
            "GMD" => Some(Currency::GMD),
            "GNF" => Some(Currency::GNF),
            "GTQ" => Some(Currency::GTQ),
            "GYD" => Some(Currency::GYD),
            "HKD" => Some(Currency::HKD),
            "HNL" => Some(Currency::HNL),
            "HRK" => Some(Currency::HRK),
            "HTG" => Some(Currency::HTG),
            "HUF" => Some(Currency::HUF),
            "IDR" => Some(Currency::IDR),
            "ILS" => Some(Currency::ILS),
            "INR" => Some(Currency::INR),
            "IQD" => Some(Currency::IQD),
            "IRR" => Some(Currency::IRR),
            "ISK" => Some(Currency::ISK),
            "JMD" => Some(Currency::JMD),
            "JOD" => Some(Currency::JOD),
            "JPY" => Some(Currency::JPY),
            "KES" => Some(Currency::KES),
            "KGS" => Some(Currency::KGS),
            "KHR" => Some(Currency::KHR),
            "KMF" => Some(Currency::KMF),
            "KPW" => Some(Currency::KPW),
            "KRW" => Some(Currency::KRW),
            "KWD" => Some(Currency::KWD),
            "KYD" => Some(Currency::KYD),
            "KZT" => Some(Currency::KZT),
            "LAK" => Some(Currency::LAK),
            "LBP" => Some(Currency::LBP),
            "LKR" => Some(Currency::LKR),
            "LRD" => Some(Currency::LRD),
            "LSL" => Some(Currency::LSL),
            "LYD" => Some(Currency::LYD),
            "MAD" => Some(Currency::MAD),
            "MDL" => Some(Currency::MDL),
            "MGA" => Some(Currency::MGA),
            "MKD" => Some(Currency::MKD),
            "MMK" => Some(Currency::MMK),
            "MNT" => Some(Currency::MNT),
            "MOP" => Some(Currency::MOP),
            "MRU" => Some(Currency::MRU),
            "MUR" => Some(Currency::MUR),
            "MVR" => Some(Currency::MVR),
            "MWK" => Some(Currency::MWK),
            "MXN" => Some(Currency::MXN),
            "MXV" => Some(Currency::MXV),
            "MYR" => Some(Currency::MYR),
            "MZN" => Some(Currency::MZN),
            "NAD" => Some(Currency::NAD),
            "NGN" => Some(Currency::NGN),
            "NIO" => Some(Currency::NIO),
            "NOK" => Some(Currency::NOK),
            "NPR" => Some(Currency::NPR),
            "NZD" => Some(Currency::NZD),
            "OMR" => Some(Currency::OMR),
            "PAB" => Some(Currency::PAB),
            "PEN" => Some(Currency::PEN),
            "PGK" => Some(Currency::PGK),
            "PHP" => Some(Currency::PHP),
            "PKR" => Some(Currency::PKR),
            "PLN" => Some(Currency::PLN),
            "PYG" => Some(Currency::PYG),
            "QAR" => Some(Currency::QAR),
            "RON" => Some(Currency::RON),
            "RSD" => Some(Currency::RSD),
            "RUB" => Some(Currency::RUB),
            "RWF" => Some(Currency::RWF),
            "SAR" => Some(Currency::SAR),
            "SBD" => Some(Currency::SBD),
            "SCR" => Some(Currency::SCR),
            "SDG" => Some(Currency::SDG),
            "SEK" => Some(Currency::SEK),
            "SGD" => Some(Currency::SGD),
            "SHP" => Some(Currency::SHP),
            "SLL" => Some(Currency::SLL),
            "SOS" => Some(Currency::SOS),
            "SRD" => Some(Currency::SRD),
            "SSP" => Some(Currency::SSP),
            "STN" => Some(Currency::STN),
            "SVC" => Some(Currency::SVC),
            "SYP" => Some(Currency::SYP),
            "SZL" => Some(Currency::SZL),
            "THB" => Some(Currency::THB),
            "TJS" => Some(Currency::TJS),
            "TMT" => Some(Currency::TMT),
            "TND" => Some(Currency::TND),
            "TOP" => Some(Currency::TOP),
            "TRY" => Some(Currency::TRY),
            "TTD" => Some(Currency::TTD),
            "TWD" => Some(Currency::TWD),
            "TZS" => Some(Currency::TZS),
            "UAH" => Some(Currency::UAH),
            "UGX" => Some(Currency::UGX),
            "USD" => Some(Currency::USD),
            "USN" => Some(Currency::USN),
            "UYI" => Some(Currency::UYI),
            "UYU" => Some(Currency::UYU),
            "UYW" => Some(Currency::UYW),
            "UZS" => Some(Currency::UZS),
            "VES" => Some(Currency::VES),
            "VND" => Some(Currency::VND),
            "VUV" => Some(Currency::VUV),
            "WST" => Some(Currency::WST),
            "XAF" => Some(Currency::XAF),
            "XAG" => Some(Currency::XAG),
            "XAU" => Some(Currency::XAU),
            "XBA" => Some(Currency::XBA),
            "XBB" => Some(Currency::XBB),
            "XBC" => Some(Currency::XBC),
            "XBD" => Some(Currency::XBD),
            "XCD" => Some(Currency::XCD),
            "XDR" => Some(Currency::XDR),
            "XOF" => Some(Currency::XOF),
            "XPD" => Some(Currency::XPD),
            "XPF" => Some(Currency::XPF),
            "XPT" => Some(Currency::XPT),
            "XSU" => Some(Currency::XSU),
            "XTS" => Some(Currency::XTS),
            "XUA" => Some(Currency::XUA),
            "XXX" => Some(Currency::XXX),
            "YER" => Some(Currency::YER),
            "ZAR" => Some(Currency::ZAR),
            "ZMW" => Some(Currency::ZMW),
            "ZWL" => Some(Currency::ZWL),
            _ => None,
        }
    }

    /// Create a currency instance from a ISO 4217 numeric code
    /// 
    /// # Example
    /// 
    /// ```
    /// use iso_currency::Currency;
    /// 
    /// assert_eq!(Currency::from_numeric(978), Some(Currency::EUR));
    /// ```
    pub fn from_numeric(numeric_code: u16) -> Option<Currency> {
        match numeric_code {
            784 => Some(Currency::AED),
            971 => Some(Currency::AFN),
            008 => Some(Currency::ALL),
            051 => Some(Currency::AMD),
            532 => Some(Currency::ANG),
            973 => Some(Currency::AOA),
            032 => Some(Currency::ARS),
            036 => Some(Currency::AUD),
            533 => Some(Currency::AWG),
            944 => Some(Currency::AZN),
            977 => Some(Currency::BAM),
            052 => Some(Currency::BBD),
            050 => Some(Currency::BDT),
            975 => Some(Currency::BGN),
            048 => Some(Currency::BHD),
            108 => Some(Currency::BIF),
            060 => Some(Currency::BMD),
            096 => Some(Currency::BND),
            068 => Some(Currency::BOB),
            984 => Some(Currency::BOV),
            986 => Some(Currency::BRL),
            044 => Some(Currency::BSD),
            064 => Some(Currency::BTN),
            072 => Some(Currency::BWP),
            933 => Some(Currency::BYN),
            084 => Some(Currency::BZD),
            124 => Some(Currency::CAD),
            976 => Some(Currency::CDF),
            947 => Some(Currency::CHE),
            756 => Some(Currency::CHF),
            948 => Some(Currency::CHW),
            990 => Some(Currency::CLF),
            152 => Some(Currency::CLP),
            156 => Some(Currency::CNY),
            170 => Some(Currency::COP),
            970 => Some(Currency::COU),
            188 => Some(Currency::CRC),
            931 => Some(Currency::CUC),
            192 => Some(Currency::CUP),
            132 => Some(Currency::CVE),
            203 => Some(Currency::CZK),
            262 => Some(Currency::DJF),
            208 => Some(Currency::DKK),
            214 => Some(Currency::DOP),
            012 => Some(Currency::DZD),
            818 => Some(Currency::EGP),
            232 => Some(Currency::ERN),
            230 => Some(Currency::ETB),
            978 => Some(Currency::EUR),
            242 => Some(Currency::FJD),
            238 => Some(Currency::FKP),
            826 => Some(Currency::GBP),
            981 => Some(Currency::GEL),
            936 => Some(Currency::GHS),
            292 => Some(Currency::GIP),
            270 => Some(Currency::GMD),
            324 => Some(Currency::GNF),
            320 => Some(Currency::GTQ),
            328 => Some(Currency::GYD),
            344 => Some(Currency::HKD),
            340 => Some(Currency::HNL),
            191 => Some(Currency::HRK),
            332 => Some(Currency::HTG),
            348 => Some(Currency::HUF),
            360 => Some(Currency::IDR),
            376 => Some(Currency::ILS),
            356 => Some(Currency::INR),
            368 => Some(Currency::IQD),
            364 => Some(Currency::IRR),
            352 => Some(Currency::ISK),
            388 => Some(Currency::JMD),
            400 => Some(Currency::JOD),
            392 => Some(Currency::JPY),
            404 => Some(Currency::KES),
            417 => Some(Currency::KGS),
            116 => Some(Currency::KHR),
            174 => Some(Currency::KMF),
            408 => Some(Currency::KPW),
            410 => Some(Currency::KRW),
            414 => Some(Currency::KWD),
            136 => Some(Currency::KYD),
            398 => Some(Currency::KZT),
            418 => Some(Currency::LAK),
            422 => Some(Currency::LBP),
            144 => Some(Currency::LKR),
            430 => Some(Currency::LRD),
            426 => Some(Currency::LSL),
            434 => Some(Currency::LYD),
            504 => Some(Currency::MAD),
            498 => Some(Currency::MDL),
            969 => Some(Currency::MGA),
            807 => Some(Currency::MKD),
            104 => Some(Currency::MMK),
            496 => Some(Currency::MNT),
            446 => Some(Currency::MOP),
            929 => Some(Currency::MRU),
            480 => Some(Currency::MUR),
            462 => Some(Currency::MVR),
            454 => Some(Currency::MWK),
            484 => Some(Currency::MXN),
            979 => Some(Currency::MXV),
            458 => Some(Currency::MYR),
            943 => Some(Currency::MZN),
            516 => Some(Currency::NAD),
            566 => Some(Currency::NGN),
            558 => Some(Currency::NIO),
            578 => Some(Currency::NOK),
            524 => Some(Currency::NPR),
            554 => Some(Currency::NZD),
            512 => Some(Currency::OMR),
            590 => Some(Currency::PAB),
            604 => Some(Currency::PEN),
            598 => Some(Currency::PGK),
            608 => Some(Currency::PHP),
            586 => Some(Currency::PKR),
            985 => Some(Currency::PLN),
            600 => Some(Currency::PYG),
            634 => Some(Currency::QAR),
            946 => Some(Currency::RON),
            941 => Some(Currency::RSD),
            643 => Some(Currency::RUB),
            646 => Some(Currency::RWF),
            682 => Some(Currency::SAR),
            090 => Some(Currency::SBD),
            690 => Some(Currency::SCR),
            938 => Some(Currency::SDG),
            752 => Some(Currency::SEK),
            702 => Some(Currency::SGD),
            654 => Some(Currency::SHP),
            694 => Some(Currency::SLL),
            706 => Some(Currency::SOS),
            968 => Some(Currency::SRD),
            728 => Some(Currency::SSP),
            930 => Some(Currency::STN),
            222 => Some(Currency::SVC),
            760 => Some(Currency::SYP),
            748 => Some(Currency::SZL),
            764 => Some(Currency::THB),
            972 => Some(Currency::TJS),
            934 => Some(Currency::TMT),
            788 => Some(Currency::TND),
            776 => Some(Currency::TOP),
            949 => Some(Currency::TRY),
            780 => Some(Currency::TTD),
            901 => Some(Currency::TWD),
            834 => Some(Currency::TZS),
            980 => Some(Currency::UAH),
            800 => Some(Currency::UGX),
            840 => Some(Currency::USD),
            997 => Some(Currency::USN),
            940 => Some(Currency::UYI),
            858 => Some(Currency::UYU),
            927 => Some(Currency::UYW),
            860 => Some(Currency::UZS),
            928 => Some(Currency::VES),
            704 => Some(Currency::VND),
            548 => Some(Currency::VUV),
            882 => Some(Currency::WST),
            950 => Some(Currency::XAF),
            961 => Some(Currency::XAG),
            959 => Some(Currency::XAU),
            955 => Some(Currency::XBA),
            956 => Some(Currency::XBB),
            957 => Some(Currency::XBC),
            958 => Some(Currency::XBD),
            951 => Some(Currency::XCD),
            960 => Some(Currency::XDR),
            952 => Some(Currency::XOF),
            964 => Some(Currency::XPD),
            953 => Some(Currency::XPF),
            962 => Some(Currency::XPT),
            994 => Some(Currency::XSU),
            963 => Some(Currency::XTS),
            965 => Some(Currency::XUA),
            999 => Some(Currency::XXX),
            886 => Some(Currency::YER),
            710 => Some(Currency::ZAR),
            967 => Some(Currency::ZMW),
            932 => Some(Currency::ZWL),
            _ => None,
        }
    }
}

impl std::fmt::Debug for Currency {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.code())
    }
}

impl std::fmt::Display for Currency {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}

#[cfg(test)]
mod tests {
    use crate::{Currency};

    #[test]
    fn return_numeric_code() {
        assert_eq!(Currency::EUR.numeric(), 978);
        assert_eq!(Currency::BBD.numeric(), 52);
        assert_eq!(Currency::XXX.numeric(), 999);
    }

    #[test]
    fn return_name() {
        assert_eq!(Currency::EUR.name(), "Euro");
        assert_eq!(Currency::BGN.name(), "Bulgarian lev");
        assert_eq!(Currency::USD.name(), "United States dollar");
    }

    #[test]
    fn return_code() {
        assert_eq!(Currency::EUR.code(), "EUR");
    }

    #[test]
    fn from_code() {
        assert_eq!(Currency::from_code("EUR"), Some(Currency::EUR));
        assert_eq!(Currency::from_code("SEK"), Some(Currency::SEK));
        assert_eq!(Currency::from_code("BGN"), Some(Currency::BGN));
        assert_eq!(Currency::from_code("AAA"), None);
    }

    #[test]
    fn from_numeric() {
        assert_eq!(Currency::from_numeric(999), Some(Currency::XXX));
        assert_eq!(Currency::from_numeric(052), Some(Currency::BBD));
        assert_eq!(Currency::from_numeric(978), Some(Currency::EUR));
        assert_eq!(Currency::from_numeric(123), None);
    }

    #[test]
    fn used_by() {
        assert_eq!(Currency::BGN.used_by(), vec!["Bulgaria"]);
        assert_eq!(
            Currency::CHF.used_by(),
            vec!["Liechtenstein", "Switzerland"]
        );
    }

    #[test]
    fn symbol() {
        assert_eq!(format!("{}", Currency::EUR.symbol()), "€");
        assert_eq!(format!("{}", Currency::XXX.symbol()), "¤");
    }
}
